config/routes.rb
Rails.application.routes.draw do
  resources :board_games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board_game.rb
class BoardGame < ApplicationRecord
    has_many_attached :pieces
    has_one_attached :box
    has_one_attached :rules_pdf
    validates :rules_pdf, attached: true, content_type: { in: 'application/pdf', message: 'This is not a PDF file' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/board_games_controller.rb
class BoardGamesController < ApplicationController
  before_action :set_board_game, only: %i[ show edit update destroy ]

  # GET /board_games or /board_games.json
  def index
    @board_games = BoardGame.all
  end

  # GET /board_games/1 or /board_games/1.json
  def show
  end

  # GET /board_games/new
  def new
    @board_game = BoardGame.new
  end

  # GET /board_games/1/edit
  def edit
  end

  # POST /board_games or /board_games.json
  def create
    @board_game = BoardGame.new(board_game_params)

    respond_to do |format|
      if @board_game.save
        format.html { redirect_to @board_game, notice: "Board game was successfully created." }
        format.json { render :show, status: :created, location: @board_game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @board_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /board_games/1 or /board_games/1.json
  def update
    respond_to do |format|
      if @board_game.update(board_game_params)
        format.html { redirect_to @board_game, notice: "Board game was successfully updated." }
        format.json { render :show, status: :ok, location: @board_game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @board_game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /board_games/1 or /board_games/1.json
  def destroy
    @board_game.destroy
    respond_to do |format|
      format.html { redirect_to board_games_url, notice: "Board game was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board_game
      @board_game = BoardGame.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def board_game_params
      params.require(:board_game).permit(:name, :rules, :box, :rules_pdf, :pieces)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_games_helper.rb
module BoardGamesHelper
end

app/views/board_games/_form.html.erb
<%= form_with(model: board_game, local: true) do |form| %>
  <% if board_game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board_game.errors.count, "error") %> prohibited this board_game from being saved:</h2>

      <ul>
        <% board_game.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :rules_pdf %>
    <%= form.file_field :rules_pdf %>
  </div>

  <div class="field">
    <%= form.label :box_image %>
    <%= form.file_field :box %>
  </div>

  <div class="field">
    <%= form.label :pieces_image %>
    <%= form.file_field :pieces, multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/board_games/edit.html.erb
<h1>Editing Board Game</h1>

<%= render 'form', board_game: @board_game %>

<%= link_to 'Show', @board_game %> |
<%= link_to 'Back', board_games_path %>

app/views/board_games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Board Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Box Image</th>
      <th>Download Box Image Link</th>
      <th>Pieces Images</th>
      <th>Download Pieces Image Link</th>
      <th>Download Rules Link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @board_games.each do |board_game| %>
      <tr>
        <td><%= board_game.name %></td>
        <td><%= image_tag board_game.box.variant(resize: "100x100", grayscale: "Rec709Luminance").processed %></td>  
        <td><%= link_to 'Box Image', rails_blob_path(board_game.box, disposition: "attachment") %></td>
        <td><%= image_tag board_game.pieces.last.variant(resize: "100x100", grayscale: "Rec709Luminance").processed %></td> 
        <td><%= link_to 'Pieces Images', rails_blob_path(board_game.pieces.last, disposition: "attachment") %></td>
        <td><%= link_to 'Rules PDF', rails_blob_path(board_game.rules_pdf, disposition: "attachment") %></td>
        <td><%= link_to 'Show', board_game %></td>
        <td><%= link_to 'Edit', edit_board_game_path(board_game) %></td>
        <td><%= link_to 'Destroy', board_game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Board Game', new_board_game_path %>

app/views/board_games/new.html.erb
<h1>New Board Game</h1>

<%= render 'form', board_game: @board_game %>

<%= link_to 'Back', board_games_path %>

app/views/board_games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board_game.name %>
</p>

<%= link_to 'Edit', edit_board_game_path(@board_game) %> |
<%= link_to 'Back', board_games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RegistroJuegos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>